blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
	path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.PostDetailView.as_view(), name='post-detail'),
	path('', views.PostListView.as_view(), name='post-list'),
	path('<int:post_id>/share/', views.post_share, name='post-share'),
]

djBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('blog/', include('blog.urls', namespace='blog')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.

class Post(models.Model):
	
	STATUS_CHOICES = (
		('draft', 'Удален'),
		('published', 'Опубликован'),
	)

	title = models.CharField(max_length=250, verbose_name='Заголовок')
	slug = models.SlugField(max_length=250, unique_for_date='publish', verbose_name='Идентификатор')
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='Автор')
	body = models.TextField(verbose_name='Текст')
	publish = models.DateTimeField(default=timezone.now, editable=False, verbose_name='Опубликован')
	created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
	updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
	status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft', verbose_name='Статус')

	class Meta:
		verbose_name = 'Пост'
		verbose_name_plural = 'Посты'
		ordering = ('-publish',)	

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('blog:post-detail', kwargs={
			'year': self.publish.year, 
			'month': self.publish.month, 
			'day': self.publish.day, 
			'post': self.slug})


class Comment(models.Model):
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
	name = models.CharField(max_length=80, verbose_name='Написал')
	email = models.EmailField(verbose_name='Электронная почта')
	body = models.TextField(verbose_name='Текст')
	created = models.DateTimeField(auto_now_add=True,verbose_name='Размещен')
	updated = models.DateTimeField(auto_now=True, verbose_name='Изменен')
	active = models.BooleanField(default=True,verbose_name='Активный')

	class Meta:
			verbose_name = 'Комментарий'
			verbose_name_plural = 'Комментарии'
			ordering = ('-created',)

	def __str__(self):
		return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms

from . import models

class EmailPostForm(forms.Form):
	name = forms.CharField(max_length=25)
	email = forms.EmailField()
	to = forms.EmailField()
	comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
	class Meta:
		model = models.Comment
		fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.core.mail import send_mail

from . import models
from . import forms

# Create your views here.

def post_share(request, post_id):
	post = get_object_or_404(models.Post, id=post_id, status='published')
	sent = False
	if request.method == 'POST':
		form = forms.EmailPostForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			post_url = request.build_absolute_uri(post.get_absolute_url())
			subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
			message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.title, post_url, cd['name'], cd['comments'])
			send_mail(subject, message, 'admin@myblog.com', [cd['to']])
			sent = True

	else:
		form = forms.EmailPostForm()
	
	return render(request,'blog/post_share.html', {'form': form, 'post': post, 'sent': sent}) 


class PostListView(generic.ListView):
	model = models.Post
	paginate_by = 3

	def get_queryset(self):
		return models.Post.objects.filter(status='published')

class PostDetailView(generic.DetailView,):
	
	context_object_name = 'post'

	def setup(self, request, *args, **kwargs):
		super().setup(request, *args, **kwargs)
		
		if request.method == 'POST':
			self.comment_form = forms.CommentForm(data=self.request.POST)
		else:
			self.comment_form = forms.CommentForm()

		self.blog_post = get_object_or_404(models.Post,
			slug = kwargs['post'],
			status = 'published',
			publish__year = kwargs['year'],
			publish__month = kwargs['month'],
			publish__day = kwargs['day']
		)

		self.new_comment = None
		self.comments = self.blog_post.comments.filter(active=True)

	def get_object(self):
		return self.blog_post
	
	def get_context_data(self, **kwargs):
		
		context = super().get_context_data(**kwargs)
		context.update({
			'comments': self.comments,
			'new_comment': self.new_comment,
			'comment_form': self.comment_form
		})
		return context

	
	def post(self, request, *args, **kwargs):
		if self.comment_form.is_valid():
			self.new_comment = self.comment_form.save(commit=False)
			self.new_comment.post = self.blog_post
			self.new_comment.save()
#			self.new_comment = True
			self.comment_form.full_clean()
		return super().get(request, *args, **kwargs)

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}Page title{% endblock %}</title>
  <link href="{% static "css/blog.css" %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block content %}
      Content here
    {% endblock %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
      <p>This is my blog.</p>
  </div>
</body>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %} 
 
{% block title %}{{ post.title }}{% endblock %} 
 
{% block content %} 
  
  <h1>{{ post.title }}</h1> 
  <p class="date"> 
    Published {{ post.publish }} by {{ post.author }} 
  </p> 
  {{ post.body|linebreaks }} 
  <p>
  	<a href="{% url 'blog:post-share' post.id %}">Shate this post</a>
  </p>

  {% with comments.count as total_comments %}
  	<h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
  {% endwith %}

  {% for comment in comments %}
  	<div class="comment">
  		<p class="info">
  			Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
  		</p>
  		{{ comment.body|linebreaks }}
  	</div>
  {% empty %}
  	<p>There are no comments yet.</p>
  {% endfor %}

  {% if new_comment %}
  	<h2>Your comment has been added.</h2>
  {% else %}
  	<h2>Add a new comment</h2>
  	<form action="." method="post">
  		{{ comment_form.as_p }}
  		{% csrf_token %}
  		<p><input type="submit" value="Add comment"></p>
  	</form>
  {% endif %}
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
 
{% block title %}My Blog{% endblock %}
 
{% block content %}
  <h1>My Blog</h1>
  {% for post in post_list %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=page_obj %}
{% endblock %}

blog/templates/blog/post_share.html
{% extends 'blog/base.html' %}

{% block title %}Share a Post{% endblock %}

{% block content %}
	{% if sent %}
		<h1>E-mail successfly sent</h1>
		<p>"{{ post.title }}" was successfly sent to {{ form.cleaned_data.to }}.</p>
	{% else %}
		<h1>Share "{{ post.title }}" by e-mail</h1>
		<form action="." method="post">
			{{ form.as_p }}
			{% csrf_token %}
			<input type="submit" value="Send e-mail">
		</form>
	{% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
      {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}">Next</a>
      {% endif %}
  </span>
</div>